timezone: America/Chicago
permalink: /blog/:slug

title: Andrew Li
description: >-
  I'm a student, developer, and jazz musician from Omaha. I also blog about math 
  and computer science, with an emphasis on intuition.
author:
  name: Andrew Li
  twitter: li_357
  image: /assets/images/andrewli.jpg
twitter:
  username: li_357
  card: summary_large_image
tagline: Student, developer, and musician.
baseurl: ''
url: 'https://andrewli.dev'

# for jekyll-seo-tag
social:
  name: Andrew Li
  links:
    - https://twitter.com/li_357
    - https://www.linkedin.com/in/andrew-li-622261180
    - https://github.com/Li357
    - https://stackoverflow.com/users/5647260/andrew-li

# for site use
profiles:
  - logo: assets/images/github.svg
    link: https://github.com/Li357
  - logo: assets/images/linkedin.svg
    link: https://www.linkedin.com/in/andrew-li-622261180
  - logo: assets/images/so.svg
    link: https://stackoverflow.com/users/5647260/andrew-li

plugins:
  - jekyll-inline-svg
  - jekyll-seo-tag

sass:
  sass_dir: _scss
  style: compact

svg:
  optimize: true

defaults:
  - scope:
      path: 'assets/images'
    values:
      image: true

destination: ./build
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
