timezone: America/Chicago
permalink: /blog/:slug

title: Andrew Li
description: >-
  Hi! I'm Andrew, a senior at MIT interested in computers, electronics, and jazz
author:
  name: Andrew Li
  image: /assets/images/andrewli.jpg
tagline: Engineer and musician
baseurl: ''
url: 'https://andrewli.dev'

# for jekyll-seo-tag
social:
  name: Andrew Li
  links:
    - https://www.linkedin.com/in/andrew-li-622261180
    - https://github.com/Li357
    - https://stackoverflow.com/users/5647260/andrew-li

# for site use
profiles:
  - logo: assets/images/github.svg
    link: https://github.com/Li357
  - logo: assets/images/linkedin.svg
    link: https://www.linkedin.com/in/andrew-li-622261180
  - logo: assets/images/so.svg
    link: https://stackoverflow.com/users/5647260/andrew-li

courses:
  - number: 6.111
    name: Digital Systems Lab
    description: FPGAs, testbenching, and UART/SPI/DSP galore
  - number: 6.172
    name: Performance Engineering
    description: Optimizing memory allocators, mulithreading renderering, profiling C and ASM to death
  - number: 6.131
    name: Power Electronics
    description: Analog and regulator design for go-carts motors, lighting systems, speakers
  - number: 6.602
    name: High-Frequency IC Design
    description: Matching networks, on-chip parasitics, low-noise amplifiers
  - number: 6.824
    name: Distributed Systems
    description: File systems, transactions, fault-tolerance, and a whole lotta Golang
  - number: 6.858
    name: Computer Security
    description: Binary exploitation, buffer overflows, WebAssembly, HTTPS
  - number: 21M.370
    name: Digital Instrument Design
    description: Building wacky instruments with embedded systems


plugins:
  - jekyll-inline-svg
  - jekyll-seo-tag

sass:
  sass_dir: _scss
  style: compact

svg:
  optimize: true

defaults:
  - scope:
      path: 'assets/images'
    values:
      image: true

destination: ./build

include:
  - CNAME
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
